version: "3.1"

services:
  db:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=apollo-auth-app
    ports:
      - 27017:27017
